# This is a basic workflow to help you get started with Actions

name: Update log file
on: push 
jobs:  
  update_log:    
    runs-on: ubuntu-latest    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  
          fetch-depth: 0
      - name: update the log file
        run: |          
          git log --invert-grep --grep="Updating the log.csv file" --grep="Merge branch" --pretty=format:"%h; %an; %as; %s" > log.csv
          git add .
          git config --local user.name "DBernardes"          
          git commit -m "Updating the log.csv file"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master       
      
